import { readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const templatePath = resolve(projectRoot, 'src', 'templates', 'page.html');
const outputPath = resolve(projectRoot, 'index.html');
const includePattern = /<!--\s*@include\s+([^\s]+)\s*-->/g;

async function resolveIncludes(filePath, stack = []) {
  if (stack.includes(filePath)) {
    throw new Error(`Циклический include: ${[...stack, filePath].map((item) => relative(projectRoot, item)).join(' → ')}`);
  }

  const source = await readFile(filePath, 'utf8');
  const folder = dirname(filePath);
  const includes = [...source.matchAll(includePattern)];
  let result = source;

  for (const include of includes) {
    const includePath = resolve(folder, include[1]);
    const content = await resolveIncludes(includePath, [...stack, filePath]);
    result = result.replace(include[0], () => content.trim());
  }

  return result;
}

const document = await resolveIncludes(templatePath);
const output = `<!-- Generated by npm run build from src/templates/page.html. Do not edit this file directly. -->\n${document.trim()}\n`;
await writeFile(outputPath, output, 'utf8');
console.log(`Built ${relative(projectRoot, outputPath)} from semantic fragments.`);
