import { readFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bundleCss, bundleJs } from './bundle.mjs';

export const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const outputPath = resolve(projectRoot, 'index.html');

const templatePath = resolve(projectRoot, 'src', 'templates', 'page.html');
const directivePattern = /<!--\s*@(include|styles|scripts)\s+([^\s]+)\s*-->/g;

function embed(tag, attributes, content) {
  if (content.toLowerCase().includes(`</${tag}`)) {
    throw new Error(`Внутри встраиваемого <${tag}> найден закрывающий тег </${tag}>.`);
  }

  return `<${tag}${attributes}>\n${content}\n</${tag}>`;
}

// Стили и сценарии встраиваются в страницу: ей хватает одного запроса, чтобы показаться и заработать.
const inline = {
  styles: async (filePath) => embed('style', '', await bundleCss(filePath)),
  scripts: async (filePath) => embed('script', ' type="module"', await bundleJs(filePath))
};

async function resolveDirectives(filePath, stack = []) {
  if (stack.includes(filePath)) {
    throw new Error(`Циклический include: ${[...stack, filePath].map((item) => relative(projectRoot, item)).join(' → ')}`);
  }

  const source = await readFile(filePath, 'utf8');
  const folder = dirname(filePath);
  let result = source;

  for (const [directive, kind, target] of source.matchAll(directivePattern)) {
    const targetPath = resolve(folder, target);
    const content = kind === 'include'
      ? await resolveDirectives(targetPath, [...stack, filePath])
      : await inline[kind](targetPath);
    result = result.replace(directive, () => content.trim());
  }

  return result;
}

export async function renderPage() {
  const document = await resolveDirectives(templatePath);
  return `<!-- Generated by npm run build from src/templates/page.html. Do not edit this file directly. -->\n${document.trim()}\n`;
}
